### ISSUE TITLE
Add user-defined public identifier for templates and elements

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#104]
We plan to add a user-defined public identifier for fields (https://github.com/metadatacenter/cedar-project/issues/786).

Do we want to support the same for templates and elements?

**Comment by graybeal** [comment]
A possible use case is importing templates or elements from another source. If those templates or elements have local IDs, this will let us (a) display those IDs, and (b) make sure we keep the same CEDAR identifier for the same template or element. (That is, we can use the external identifier to make one-for-one replacements, or to recognize a version upgrade.)

**Comment by martinjoconnor** [comment]
We will definitely add to model for 2.1. May need to punt on full front end support for templates and elements until 2.2.
