### ISSUE TITLE
1.6 Model Updates/Hardening

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#120]
Parent of metadatacenter/cedar-model-validation-library#71
Parent of metadatacenter/cedar-model-validation-library#107
Parent of metadatacenter/cedar-model-validation-library#114
Parent of metadatacenter/cedar-model-validation-library#117
Parent of metadatacenter/cedar-model-validation-library#118
Parent of metadatacenter/cedar-model-validation-library#119
Parent of metadatacenter/cedar-model-validation-library#122
Parent of metadatacenter/cedar-model-validation-library#123
Parent of metadatacenter/cedar-model-validation-library#125

Parent of metadatacenter/cedar-project#942
Parent of metadatacenter/cedar-resource-server#35
Parent of metadatacenter/cedar-resource-server#66
Parent of metadatacenter/cedar-project#851

Parent of metadatacenter/cedar-template-editor#856
Parent of metadatacenter/cedar-template-editor#857
Parent of metadatacenter/cedar-template-editor#858

**Comment by cedaradmin** [comment]
This was a Waffle-based epic.
