### ISSUE TITLE
Add model version to templates

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#16]
Add CEDAR model version to templates, elements, and fields.

Perhaps use the schema.org <tt>schemaVersion</tt> property.

Related task: #22

**Comment by martinjoconnor** [comment]
We should discuss to see if it would be possible to get this into 1.1.

**Comment by marcosmro** [comment]
Yes, I'll include it into release 1.1. As discussed, we will start with version number 1.1.
