### ISSUE TITLE
Bad model encoding of multi-value fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#31]
Our current schema representation for fields with multiple possible values is incorrect. Currently checkboxes and multiple-choice lists are the only two CEDAR field types that can have multiple values. (Note that our instance representation for these fields is correct, as is our representation of radio-buttons and single-choice lists, which have single instance values only. Also, our representation of multi-instance fields is fine. )

If we have, say, a <tt>Choices</tt> field that is a multiple-choice list then the schema could look as follows:
```
"choices": {
    "@type": "https://schema.metadatacenter.org/core/TemplateField",
    "@context": { ... },
    "type": "object",
    "title": "Choices field schema",
    "description": "Choices field schema autogenerated by the CEDAR Template Editor",
    "_ui": {
        "title": "Choices",
        "description": "",
        "inputType": "checkbox"
    },
    "_valueConstraints": {
        "requiredValue": false,
        "literals": [ { "label": "O1" }, { "label": "O2" }  ],
        "multipleChoice": true
    },
    "properties": {
        "@type": { ... },
        "@value": { "type": [ "array", "null" ] },
    },
    "required": [ "@value" ],
    ...
}
```

This is incorrect because it implies that the final instance should have a <tt>@value</tt> field that is either <tt>null</tt> or an array, e.g.,

    "choices": { "@value": [ "O1", "O2" ] }

However, the actual instance value will be something like:

      "choices": [ { "@value":  "O1" }, { "@value":  "O2" } ]

Making the field value schema an array as follows:

    "choices": {
        "type": "array",
        "items": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": { ... },
          "title": "Choices field schema",
          "_ui": { 
            "title": "Choices",
            "description": "",
            "inputType": "checkbox"
          },
          "_valueConstraints": { ... },
         ...
      }
    }

looks superficially correct but it is not because it implies that the value of the field is an array of checkbox field values. Instead the value of the field is an array of literal values (or URIs in the case of @id value fields).

An initial suggestion would be to pull the <tt>_ui</tt> and <tt>_valueConstraints</tt> fields up a level for these checkbox and multiple choice fields, e.g.,

    "choices": {
        "type": "array",
         "_ui": { 
            "title": "Choices",
            "description": "",
            "inputType": "checkbox"
         },
        "_valueConstraints": { ... },
        "items": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": { ... },
          "title": "Choices field schema",
         ...
      }
    }

For fields with multiple-values we would then need to generate a schema specification for values on field instances that specifies an array of JSON objects containing @value fields (or an array containing objects with @id fields for URI values).

**Comment by johardi** [comment]
I think we can put more fields outside `items` like `@type`, `@context`, provenance fields, etc., since the essential keywords for item validation are `type`, `properties`, `required`.

**Comment by martinjoconnor** [comment]
Tentative plan for discussion (and ignoring _ui, _valueConstraints, and  JSON-LD @type and @context fields for the moment).

Say we have a single instance field with a URI value specified in JSON Schema as follows:

{
  "title": "Home Page", "description": "Home page template field",
  "type": "object",
  "properties": { 
   "@id": { "type": "string", "format": "uri" },
   "pav:createdOn": { "type": ["string", "null"], "format": "date-time" },
   "pav:createdBy": { "type": ["string", "null"], "format": "uri" },
   "pav:lastUpdatedOn": { "type": ["string", "null"], "format": "date-time" },
   "oslc:modifiedBy": { "type": ["string", "null"], "format": "date-time" }
  },
  "required": [ "@id" ], "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-04/schema#"
}

Conforming value is obviously something like:

    { "@id": "http://example.com/A1" }

If we want multiple-values, e.g.,

    [ { "@id": "http://example.com/A1" }, { "@id": "http://example.com/A2" } ]

then the field schema could be:

{
  "title": "Home Pages", "description": "Home page template field (multi-value)",
  "type": "array",
  "items": {
    "properties": { 
       "@id": { "type": "string", "format": "uri" },
       "pav:createdOn": { "type": ["string", "null"], "format": "date-time" },
       "pav:createdBy": { "type": ["string", "null"], "format": "uri" },
       "pav:lastUpdatedOn": { "type": ["string", "null"], "format": "date-time" },
       "oslc:modifiedBy": { "type": ["string", "null"], "format": "date-time" }
    },
    "required": [ "@id" ], "additionalProperties": false
  }
  "$schema": "http://json-schema.org/draft-04/schema#"
}

It would suggest moving _ui, _valueConstraints and JSON-LD @type and @context fields upwards, e.g.,

{
  "@type": "https://schema.metadatacenter.org/core/TemplateField",
  "@context": { ... },
  "_ui": {
        "title": "Choices",
        "description": "",
        "inputType": "checkbox"
   },
   "_valueConstraints": {
        "requiredValue": false,
        "literals": [ { "label": "Primary" }, { "label": "Secondary" }  ],
        "multipleChoice": true
   },
  "title": "Home Pages", "description": "Home page template field (multi-value)",
  "type": "array",
  "items": {
    "properties": { 
       "@id": { "type": "string", "format": "uri" },
       "pav:createdOn": { "type": ["string", "null"], "format": "date-time" },
       "pav:createdBy": { "type": ["string", "null"], "format": "uri" },
       "pav:lastUpdatedOn": { "type": ["string", "null"], "format": "date-time" },
       "oslc:modifiedBy": { "type": ["string", "null"], "format": "date-time" }
    },
    "required": [ "@id" ], "additionalProperties": false
  }
  "$schema": "http://json-schema.org/draft-04/schema#"
}

@marcosmro and @johardi does that look plausible?

**Comment by martinjoconnor** [comment]
I tried the above on https://jsonschemalint.com and it seems to do the right thing.
