### ISSUE TITLE
Some nested value-recommended fields behave strangely

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#4]
Use the following BioSample instance to reproduce:

https://cedar.staging.metadatacenter.net/instances/edit/https://repo.staging.metadatacenter.net/template-instances/9a34cd56-4b22-4a61-82e6-5eac8b893655

The value-recommended name field inside of the nested Optional Attribute element is a little funky. 

In some cases the JSON does not show a value for the field even when a value is clearly visible. This can be seen also when clicking the Validate button. (I can't reliably reproduce this issue.)

An additional odd behaviour can be seen in the following image. The empty parenthesis content for the suggestion is invalid:

**Comment by martinjoconnor** [comment]
Related to #3.

**Comment by marcosmro** [comment]
I couldn't reproduce this issue, but I've seen that now it's not possible to remove a value after choosing it. The value is removed from the UI, but not from the model.

**Comment by martinjoconnor** [comment]
Duplicate of #571
