### ISSUE TITLE
Patch _valueLabel field in templates and instances

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-model-validation-library#42]
Patch resources in staging/production according to the fix implemented for metadatacenter/cedar-model-validation-library/issues/32.

Template elements don't need to be patched.

For templates, add the "rdfs" namespace to the "properties.@context.properties" field. Example:

```
 {
  "@id": "https://repo.metadatacenter.orgx/templates/e21b7b69-317d-4e99-af69-683969818931",
  "@type": "https://schema.metadatacenter.org/core/Template",
  ...
  "properties": {
    "@context": {
      "properties": {
        "rdfs": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2000/01/rdf-schema#"
          ]
        },
  ...
}
```

For template fields, rename the "properties._valueLabel" field to "properties.rdfs:label". Example:

```
{
  "disease": {
    ...
    "properties": {
      ...
      "rdfs:label": {
        "type": [
          "string",
          "null"
        ]
      },
      ...
    }
  }
}
```

**Comment by martinjoconnor** [comment]
Done for templates but not yet done for instances.
