### ISSUE TITLE
Extend schema validation to support attribute/value field type

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#70]
Extend validation schema to cater for template and instance extensions that deal with attribute/value fields.

Main description of extensions here:
 
https://github.com/metadatacenter/cedar-model-validation-library/issues/54

See also:

https://github.com/metadatacenter/cedar-model-validation-library/issues/69

**Comment by ahmadchan** [comment]
AIRR Data Representation efforts for AIRR data representation and validation as discussed in April 19th Call. http://docs.airr-community.org/en/latest/formats/overview.html

**Comment by martinjoconnor** [comment]
See the final specification for attribute-value fields here :

https://docs.google.com/document/d/1mfrnIOvmzeA6nWIQbE6zuMmac2D52hnS4Pu6IrQs-Hg/edit#heading=h.tkfe0s6vyd8s

**Comment by martinjoconnor** [comment]
See also https://github.com/metadatacenter/cedar-model-validation-library/issues/79
