### ISSUE TITLE
Look for UUID-named fields in artifacts and remove

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#71]
We had an old bug that created field with UUID names (e.g., ```819dd88d-94d6-4690-a221-ef6301921854```) and some remain. 

Look for fields with this name in the validation script.

Also look for @context properties with this name.

If only a small number of such fields exist we can hand patch. Otherwise may be able to find real name from ```schema:name``` property in the field schema.

**Comment by johardi** [comment]
Running a quick scan script gave me these numbers (per October 31):
- 200 out of 1,040 templates contain UUID field names
- 178 out of 1,512 template elements contain UUID field names
- none of the template fields contains a UUID field name

Hand patch them may not be the best solution.

**Comment by martinjoconnor** [comment]
My guess (which may be incorrect) is that the UUID field names have no corresponding actual fields - that is, the names exist in the @context and 'required'  arrays only.

Is this true? If so, it may be possible to excise them more easily.

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-template-editor/issues/848
