### ISSUE TITLE
Field schema should require non-empty name

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#73]
The JSON Schema specifying CEDAR fields should require a non-empty ```schema:name``` in instance.

It seems that the generated JSON Schema is not requiring this, e.g.,

```
"My text field": {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "@id": "tmp-1516944013678-27951",
    "@type": "https://schema.metadatacenter.org/core/TemplateField",
    "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "schema:name": { "@type": "xsd:string" },
        "schema:description": { "@type": "xsd:string" },
```

```schema:name``` schema should be ```{ "@type": "xsd:string", "minLength": 1 }```

**Comment by graybeal** [comment]
Does this apply to non-required fields? if the user does not fill out the field, but it isn't required, I don't think that's an error.

**Comment by johardi** [comment]
I'm closing this-- assuming [our current uber-schema](https://github.com/metadatacenter/cedar-model-validation-library/blob/develop/src/main/resources/template-schema.json) at line 122  followed by line 252-261 have already answered the issue.
