### ISSUE TITLE
Field and element name, description handling

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#83]
When fields are added to a template or element and their names and descriptions are changed we currently change the field internally (via schema:name and schema:description and _ui fields). 

With 1st class fields and versioning we now need to option to treat embedded fields as immutable so that name or description changes do no get reflected inside the field itself. The same principle applies to elements.

Currently we have a _ui.propertyLabel in templates and elements that maps element names to display names for enclosed elements. We need to use that to hold field display names. 

(Perhaps rename _ui.propertyLabel to _ui.propertyName, and use _ui.propertyDescription for description entries.)

**Comment by willrett** [comment]
branch issue/feature-750

**Comment by willrett** [comment]
Added _ui.propertyDescriptions to hold descriptions values.  Labels and descriptions for  first class fields and elements go into the enclosing template or element.
