### ISSUE TITLE
Version CDEs

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#84]
CEDAR artifacts are versioned following the major/minor/patch format (e.g., 2.3.1) described in the Semantic Versioning recommendations (https://semver.org/). Some external artifacts (e.g., caDSR CDEs) do not have a patch component (e.g., 2.4).

We need to allow externally-uploaded artifacts with a missing patch component to work.

For simplicity, we will not initially attempt to handle other cases (e.g, 3.2.3-RC2).

Also we will not allow artifact versions created via the GUI to be incomplete.

**Comment by martinjoconnor** [comment]
Another option is to simply add a ".0" patch and strictly enforce semantic versioning.

**Comment by graybeal** [comment]
is the intention to explicitly use the semantic components? so if someone else comes along that uses non-semantic versioning, would we maintain their version separately from our own?  maybe adding an 'external version' now could be useful, to let entities in our versioning system progress independently from other systems.

**Comment by martinjoconnor** [comment]
The three components (major/minor/patch) will be explicitly managed by CEDAR. Artifacts managed by CEDAR will enforce it (in much the same way as Maven Central forces artifact versioning).

Mapping to a separate external versioning scheme (or supporting different versioning schemes) would add massive complexity. We can point to the external resource that users may be representing in CEDAR (e.g., https://github.com/metadatacenter/cedar-project/issues/780 and https://github.com/metadatacenter/cedar-project/issues/783) but it is up to users to map their metadata to CEDAR I would argue.  Maintaining multiple reconciliation pointers in CEDAR to information about those resources  (e.g., source version, source creation time etc.) would make our lives very hard - and would violate the DRY principle.

**Comment by martinjoconnor** [comment]
For simplicity we will initially just map caDSR versions to CEDAR's scheme.
