### ISSUE TITLE
Support preferred and alternate question  text in model

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#85]
In CEDAR when a field is added to a template or element its name by default becomes the question text on the presented field in the Metadata Editor (though we can override at the level of the enclosing template or element). 

Should we add an optional attribute to CEDAR fields that captures the preferred question text?

Relevant for caDSR CDE work.

Requires metadatacenter/cedar-model-validation-library#106
Requires metadatacenter/cedar-template-editor#816

**Comment by martinjoconnor** [comment]
Notes from https://docs.google.com/document/d/1bmQzoCKRsgF8viL5Z318ZaodeTKiDq0Vfiw--fQxTP0/edit# by Denise :

Preferred Question Text: This metadata is curated and cannot be edited when using the CDE in a template, but should be used as the displayed text for users entering data into the form. It is contained in the DataElement/ REFERENCEDOCUMENTSLIST/REFERENCEDOCUMENTSLIST_ITEM/DocumentType = “Preferred Question Text” 
Note: Longer term, we need to be able to let the person designing the template have access to additional curated question texts, these are stored in Reference Documents with DocumentType = “Alternate Question Text”. Users are allowed to select this for their form instead of Preferred Question Text, but question text cannot be created de novo within the form as its important to ensure that the data is elicited with text that conveys the same meaning
Real-time Notes:
Going back within template, caDSR curates the preferred question text. When you bring element within template, that’s what’s supposed to be used. In our search results, that’s a second field that’s displayed. Called the Reference Document, has document type of referenceType.(?-Denise will provide details) The question text is very important for each element, and needs to be brought forward in addition to Field Name on the template, and instead of the Field Name for the metadata entry. (We have mapping table that might be able to support this, so that field name is not what’s shown on the form. We’ll look at it.)

**Comment by martinjoconnor** [comment]
This also related to field IDs (https://github.com/metadatacenter/cedar-project/issues/786).

In CEDAR a field name is effectively its user ID (there is an internal ID but that is not for non developer consumption).

caDSR CDEs, for example, clearly distinguish field IDs, field names and question text. CEDAR does not make this distinction currently.

**Comment by martinjoconnor** [comment]
We need to find a pre-existing property name that works here.

**Comment by marcosmro** [comment]
In our current model, we are using schema:name to store both the CDE identifier (PUBLICID) and the CDE name (LONGNAME), as follows:

`"schema:name": <PUBLICID + "-" + LONGNAME>`

Currently, we are not storing neither the CDE question text nor the CDE question alternate texts.

A possible way of extending our model to capture all this information would be to use schema:identifier to store the CDE identifier, schema:name for the CDE name, skos:prefLabel for the preferred question text, and skos:altLabel for the alternate question texts, that is:

```
"schema:identifier": <PUBLICID>,
"schema:name": <LONGNAME>,
"skos:prefLabel": <Preferred question text>, (only one value)
"skos:altLabel": <Alternate question text> (one value per alternate text)
```

Example with a real CDE:

```
"schema:identifier": "2001844",
"schema:name": "Surgical Procedure Lumpectomy Excisional Biopsy Performed",
"skos:prefLabel": "Excisional Biopsy or Lumpectomy", 
"skos:altLabel": "Was lumpectomy performed?",
"skos:altLabel": "Excisional benign breast biopsy",
"skos:altLabel": "Was localized excision of clipped lymph node performed?"
```

I am proposing to use skos:prefLabel instead of rdfs:label because the former is more specific. Both skos:prefLabel and skos:altLabel are each sub-properties of rdfs:label.

**Comment by martinjoconnor** [comment]
Note that the model validation should allow JSON arrays for both the question text (skos:prefLabel) and the alternative questions (skos:altLabel) e.g.,

    {
      "skos:prefLabel": [ "Ireland"@en, "España"@es ],
      "skos:altLabel": [ "Was lumpectomy performed?", "Excisional benign breast biopsy", "Was localized excision of clipped lymph node performed?" ]
      ... 
    }

The first will allow future support for language tags and the second will nicely capture the order of alternate questions.

**Comment by martinjoconnor** [comment]
Tasks cedar-model-validation-library#106
and metadatacenter/cedar-template-editor#816 will implement this feature at the model and front end, respectively.

**Comment by martinjoconnor** [comment]
As per email from Denise, their RDF mapping approach is very similar. The use ```rdfs:label``` and ```skos:altLabel``` instead of our ```skos:prefLabel``` and ```skos:altLabel``` (though they have not released their system yet).

Note that ```skos:prefLabel``` is a sub-property of ```rdfs:label```.

```
From: "Warzel, Denise (NIH/NCI) [E]" <warzeld@mail.nih.gov>
Subject: FW: [metadatacenter/cedar-model-validation-library] Support preferred question text in model (#85)
Date: September 10, 2018 at 3:28:32 PM PDT
To: "Fragoso, Gilberto (NIH/NCI) [E]" <fragosog@mail.nih.gov>, "Marcos Martinez Romero" <marcosmr@stanford.edu>
Cc: John Graybeal <jgraybeal@stanford.edu>, "Lu, Zhengwu (NIH/NCI) [C]" <zhengwu.lu@nih.gov>

Hi Gilberto and Marcos
 
I am raising this question to Gilberto because we have an RDF representation of the CDEs at NCI, and we made some decision about rdf labels for the fields too.  We have not gone into production with this schema yet, so there is an opportunity to “harmonize” our labels.
 
We currently used rdfs:label for the CDE Long Name, and skos:altLabel for ALL the question texts along with an OWL axiom to specify which ones were the Preferred vs the Alternate.
 
I wouldn’t be opposed to skos:prefLabel for the Preferred Question Text and skos:altLabel for the others, but I defer to Gilberto to weigh in.
 
 
cmdr:DE2001822 rdfs:label "Patient Hospitalization Ind-2" ;
               cmdr:publicId "2001822" ;
               a rdfs:Class  ;
               isomdr:version "3" ;
               skos:definition "the yes/no indicator that asks whether the patient was hospitalized." ;
               isomdr:registration_status "Qualified" ;
               isomdr:administration_status "RELEASED" ;
               cmdr:used_by "PT_HOSP_IND2" ,"PT_HOSP_IND2" ,"NRG" ,"NHLBI" ,"DCP" ,"NRG" ,"NRG" ,"DCP" ,"CTEP" ,"CTEP" ,"CTEP" ,"CTEP" ,"CTEP" ,"CTEP" ,"NRG" ;
               skos:altLabel "Was the patient hospitalized for 24 hours or more?" ;
               skos:altLabel "Did the patient require hospitalization" ;
               skos:altLabel "Hospitalized for other reasons" ;
               skos:altLabel "Was the patient hospitalized?" ;
               skos:altLabel "Was the recipient hospitalized for the HCT episode?" ;
               skos:altLabel "Was the recipient hospitalized?" ;
 
….
 a owl:Axiom ;
     owl:annotatedProperty skos:altLabel ;
     owl:annotatedSource cmdr:DE2001822 ;
     owl:annotatedTarget "Was the patient hospitalized for 24 hours or more?" ;
     cmdr:alternate_name_type "Preferred Question Text" .
     
[ a owl:Axiom ;
     owl:annotatedProperty skos:altLabel ;
     owl:annotatedSource cmdr:DE2001822 ;
     owl:annotatedTarget "Did the patient require hospitalization" ;
     cmdr:alternate_name_type "Alternate Question Text" .
 
etc
```

**Comment by graybeal** [comment]
I think one of our drivers was staying out of OWL axioms, which can make things pretty complicated.

**Comment by martinjoconnor** [comment]
Closing this. We can talk about a future alignment with caDSR RDF generation if needed.
