### ISSUE TITLE
Categorizing CEDAR artifacts

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#89]
Currently folders represent the primary way for users to organize resources. One could imagine being able semantically categorize and subcategorize or tag resources.

Relevant for CDE fields, for example, where some users may only be interested in finding CDE-based fields.

We need to determine a generic way of doing this.

**Comment by martinjoconnor** [comment]
The Context field for caDSR CDEs is also a use case. It seems to identify the organization (or subunit thereof) who developed the CDE.

**Comment by graybeal** [comment]
Reference #780

**Comment by martinjoconnor** [comment]
Categorization task now ongoing. Search for 'Categories' label to find involved tasks.
